import * as entities from 'src/entities';
import * as seeders from './tables-seeders';

import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';

@Module({
    imports: [
        TypeOrmModule.forFeature([
            entities.User,
            entities.Game,
            entities.Group,
            entities.Match,
            entities.Performance,
            entities.Player,
            entities.Preset,
            entities.Prize,
            entities.Suspension,
            entities.Team,
            entities.Tournament,
            entities.ActiveRoster,
            entities.GroupRule,
            entities.GroupStanding,
            entities.LadderStanding,
            entities.Ladder,
            entities.Map,
            entities.Roster,
            entities.TiebrakerRule,
            entities.TournamentAdmin,
        ]),
    ],
    providers: [
        seeders.UsersSeeder,
        seeders.GamesSeeder,
        seeders.GroupsSeeder,
        seeders.MatchesSeeder,
        seeders.PerformancesSeeder,
        seeders.PlayersSeeder,
        seeders.PresetsSeeder,
        seeders.PrizesSeeder,
        seeders.SuspensionsSeeder,
        seeders.TeamsSeeder,
        seeders.TournamentsSeeder,
        seeders.ActiveRosterSeeder,
        seeders.GroupRuleSeeder,
        seeders.GroupStandingSeeder,
        seeders.LadderStandingSeeder,
        seeders.LadderSeeder,
        seeders.MapSeeder,
        seeders.RosterSeeder,
        seeders.TiebrakerRuleSeeder,
        seeders.TournamentAdminSeeder,
    ],
    exports: [
        seeders.UsersSeeder,
        seeders.GamesSeeder,
        seeders.GroupsSeeder,
        seeders.MatchesSeeder,
        seeders.PerformancesSeeder,
        seeders.PlayersSeeder,
        seeders.PresetsSeeder,
        seeders.PrizesSeeder,
        seeders.SuspensionsSeeder,
        seeders.TeamsSeeder,
        seeders.TournamentsSeeder,
        seeders.ActiveRosterSeeder,
        seeders.GroupRuleSeeder,
        seeders.GroupStandingSeeder,
        seeders.LadderStandingSeeder,
        seeders.LadderSeeder,
        seeders.MapSeeder,
        seeders.RosterSeeder,
        seeders.TiebrakerRuleSeeder,
        seeders.TournamentAdminSeeder,
    ],
})
export class SeedersModule {}
